- name: Deploy and Test {{ run_name }}
  hosts: all
  become: yes
  tasks:
  - name: Pull {{ container_name }} image
    shell: "docker pull {{ image_url }}"

  - name: Run the image
    shell: "docker run --name {{ instance_name }} {{ image_url }}"

  - name: Create Additional Artifacts
    shell: docker images > {{ host_data_out }}/docker_images.out; docker ps -a > {{ host_data_out }}/docker_ps_a.out; cp /etc/os-release {{ host_data_out }}/os-release

