apiVersion: v1
kind: Template
labels:
  template: cvengine-builder
metadata:
  annotations:
    description: cvengine container
    iconClass: cvengine
    tags: instant-app
  name: cvengine-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: cvengine
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: cvengine
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cvengine:latest
    resources: {}
    source:
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        env:
          - name: CONTAINER_NAME
            value: cvengine
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/CentOS-PaaS-SIG/cvengine.git
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
